FROM nvcr.io/nvidia/pytorch:25.09-py3

WORKDIR /app

# * Installing packages like this will do so system wide. That way we can use the pre-baked packages that come with the base image
RUN pip install fastapi uvicorn[standard] \
    pydantic python-multipart \
    pillow diffusers transformers \
    huggingface \
    peft \
    sentencepiece \
    nvidia-ml-py

COPY . .

ENV MODEL_DIR=/models
ENV GENERATED_IMAGE_PATH=/app/app
ENV PORT=80
EXPOSE 80

CMD ["python", "-m", "app"]